### ISSUE TITLE
How to solve [generate:hero-icons] path not found (yemenopensource\hero-icons\src\config/../vendor/blade-ui-kit/blade-heroicons/resources/svg)

### ISSUE THREAD

**Issue by doctor-he** [YemenOpenSource/hero-icons#1]
```
 php artisan generate:hero-icons
Scanning: D:\GeneralProjects\mahsobah\mahsobah\vendor\yemenopensource\hero-icons\src\config/../vendor/blade-ui-kit/blade-heroicons/resources/svg

   ErrorException 

  scandir(D:\GeneralProjects\mahsobah\mahsobah\vendor\yemenopensource\hero-icons\src\config/../vendor/blade-ui-kit/blade-heroicons/resources/svg): The system cannot find the path 
specifi (code: 3)

  at vendor\yemenopensource\hero-icons\src\Console\Commands\GenerateHeroIconsClass.php:42
     38▕
     39▕         $this->line('Scanning: ' . $directory);
     40▕
     41▕         // Get the file names from the directory
  ➜  42▕         $files = scandir($directory);
     43▕
     44▕         // Initialize an array to store the constant names
     45▕         $constants = array();
     46▕

  1   vendor\yemenopensource\hero-icons\src\Console\Commands\GenerateHeroIconsClass.php:42

  2   vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
      YOS\HeroIcons\Console\Commands\GenerateHeroIconsClass::handle()
```

**Comment by muath-ye** [comment]
publish the config using 

```
php artisan vendor:publish --provider="YOS\HeroIcons\ServiceProvider" --tag="config"
```

or check the path of svg files of `blade-ui-kit/blade-heroicons` package

![image](https://github.com/YemenOpenSource/hero-icons/assets/34031333/3ab7fa43-7fe9-4751-a977-66f99ce4e848)

as in the image the path on config should be like following

```
// config/heroicons.php

'blade-ui-kit-path' => __DIR__ . '/../vendor/blade-ui-kit/blade-heroicons/resources/svg',
```

after that re run the generator

**Comment by doctor-he** [comment]
> publish the config using
> 
> ```
> php artisan vendor:publish --provider="YOS\HeroIcons\ServiceProvider" --tag="config"
> ```
> 
> or check the path of svg files of `blade-ui-kit/blade-heroicons` package
> 
> ![image](https://private-user-images.githubusercontent.com/34031333/293326750-3ab7fa43-7fe9-4751-a977-66f99ce4e848.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4MzYwMDMsIm5iZiI6MTcwMzgzNTcwMywicGF0aCI6Ii8zNDAzMTMzMy8yOTMzMjY3NTAtM2FiN2ZhNDMtN2ZlOS00NzUxLWE5NzctNjZmOTljZTRlODQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDA3NDE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjM2RiYWZmMzdhZTQ5MzU3MGRmY2U4M2FlNjIyNjg2ZjQ5ZWRkZGI1NjQzZDFkNTE0MTU5MzliOWZmZWEzMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MR6ioboRvQjTC0nG0ui_WrkjLL7Q_C9eRoALzgIKJ8Q)
> 
> as in the image the path on config should be like following
> 
> ```
> // config/heroicons.php
> 
> 'blade-ui-kit-path' => __DIR__ . '/../vendor/blade-ui-kit/blade-heroicons/resources/svg',
> ```
> 
> after that re run the generator

Thanks, it worked for me after publish the config
